### ISSUE TITLE
idl2js usage? errors?

### ISSUE THREAD

**Issue by ccrashes** [PrVrSs/idl2js#2]
Hello .
I'm trying to use idl2js to run the webassembly example :

`python3 examples/web_assembly/main.py`

No module named idl2js .

I followed the documentation for install .

Os : ubuntu 20.04

thanks

**Comment by PrVrSs** [comment]
Hello. 
Check the list of installed packages with `pip frezee` command.
try to use pip3

**Comment by ccrashes** [comment]
Thanks .

I solved this problem .

One problem with the installation is : after downloading antlr package as mentioned, `make grammar` is actually doing nothing. 
Is it mean that there would be no need to have anltr anymore ?

One more question is : Is the current code applicable to handling of other IDL files ? For example if I want to use idl2js to read the IDL specs of websockets (https://chromium.googlesource.com/chromium/blink/+/refs/heads/main/Source/modules/websockets/) what steps are required to take ?

Thank you

**Comment by ccrashes** [comment]
@PrVrSs Any update?

**Comment by PrVrSs** [comment]
Sorry for the delayed response. You don't have to worry about 'antlr' anymore; I have transferred all the logic to the 'pywebidl2' package. Feel free to open new issues if you have any questions.
